spring:
  application:
    name: insurance-events-app

  pulsar:
    client:
      # Surchargé par SPRING_PULSAR_CLIENT_SERVICE_URL en variable d'env (docker-compose)
      service-url: pulsar://localhost:6650
    defaults:
      topic:
        name: persistent://public/default/contrat-events

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
